var ARC = require('..');
var cache = new ARC(3, function(key) {return key + '@' + key;});
console.log(cache);
console.log(cache.req('key1'));
console.log(cache);
console.log(cache.req('key1'));
console.log(cache);
console.log(cache.req('key2'));
console.log(cache);
console.log(cache.req('key3'));
console.log(cache);
console.log(cache.req('key2'));
console.log(cache);
console.log(cache.req('key1'));
console.log(cache);
console.log(cache.req('key4'));
console.log(cache);
console.log(cache.req('key5'));
console.log(cache);
console.log(cache.req('key2'));
console.log(cache);
console.log(cache.req('key2'));
console.log(cache);
console.log(cache.req('key4'));
console.log(cache);